function StartNIDAQ
% This function setup NI-DAQ cards wiring, and fundamental tasks
% Terminal Definition is in SetupD

%% import NI DAQmx class
import dabs.ni.daqmx.*

%% import handles and data
global Xin
NI = Xin.D.Sys.NIDAQ;

%% System
    Xin.HW.NI.hSys = System();    
        
%% Device and Reset
    for i = 1:length(NI.Dev_Names) 
        Xin.HW.NI.hDev{i} = Device(NI.Dev_Names{i});
        Xin.HW.NI.hDev{i}.reset();
    end

%% Trigger Routing
    % Export Timebase to bridge
    C = NI.Config;
    Xin.HW.NI.hSys.connectTerms(...
        ['/', C.deviceNames, '/',  C.FrameSourceLine],...
        ['/', C.deviceNames, '/',  C.FrameBridgeLine]); 
%     Xin.HW.NI.hSys.connectTerms(...
%         ['/', C.deviceNames, '/',  C.StartSourceLine],...
%         ['/', C.deviceNames, '/',  C.StartBridgeLine]); 
%     Xin.HW.NI.hSys.connectTerms(...
%         ['/', C.deviceNames, '/',  C.TimebaseSourceLine],...
%         ['/', C.deviceNames, '/',  C.TimebaseBridgeLine]); 
    
% %% Analog Input    
% AI_Xin for Power Meter Monitor Input
    T = NI.Task_AI_Xin;
    Xin.HW.NI.T.hTask_AI_Xin = Task(T.taskName);
    Xin.HW.NI.T.hTask_AI_Xin.createAIVoltageChan(...
        T.chan(1).deviceNames,              T.chan(1).chanIDs,...
        T.chan(1).chanNames,                T.chan(1).minVal,...
        T.chan(1).maxVal,                   T.chan(1).units);   
 	Xin.HW.NI.T.hTask_AI_Xin.set(...
        'sampClkTimebaseRate',              T.base.sampClkTimebaseRate,...
        'sampClkTimebaseSrc',               T.base.sampClkTimebaseSrc);     
    Xin.HW.NI.T.hTask_AI_Xin.cfgSampClkTiming(...
        T.time.rate,                        T.time.sampleMode,...
        T.time.sampsPerChanToAcquire);
    Xin.HW.NI.T.hTask_AI_Xin.cfgDigEdgeStartTrig(...
        T.trigger.triggerSource,        	T.trigger.triggerEdge);
    Xin.HW.NI.T.hTask_AI_Xin.registerEveryNSamplesEvent(...
        T.everyN.callbackFunc,              T.everyN.everyNSamples,...
        T.everyN.readDataEnable,            T.everyN.readDataTypeOption);
    Xin.HW.NI.T.hTask_AI_Xin.start();      
    
%% Analog Output
% AO_Xin for Sound Output
    T = NI.Task_AO_Xin;
   	Xin.HW.NI.T.hTask_AO_Xin = Task(T.taskName);
   	Xin.HW.NI.T.hTask_AO_Xin.createAOVoltageChan(...
        T.chan(1).deviceNames,              T.chan(1).chanIDs,...
        T.chan(1).chanNames,                T.chan(1).minVal,...
        T.chan(1).maxVal,                   T.chan(1).units);     
 	Xin.HW.NI.T.hTask_AO_Xin.set(...
        'sampClkTimebaseRate',              T.base.sampClkTimebaseRate,...
        'sampClkTimebaseSrc',               T.base.sampClkTimebaseSrc);      
    Xin.HW.NI.T.hTask_AO_Xin.cfgSampClkTiming(...
        T.time.rate,                        T.time.sampleMode,...
        T.time.sampsPerChanToAcquire);
    Xin.HW.NI.T.hTask_AO_Xin.cfgDigEdgeStartTrig(...
        T.trigger.triggerSource,            T.trigger.triggerEdge);
%     Xin.HW.NI.T.hTask_AO_Xin.registerEveryNSamplesEvent(...
%         T.everyN.callbackFunc,              T.everyN.everyNSamples);
    Xin.HW.NI.T.hTask_AO_Xin.writeAnalogData(...
        T.write.writeData);
    Xin.HW.NI.T.hTask_AO_Xin.start();
          
%% Counter Output Triggers
% Frame Trigger
    T = NI.Task_CO_TrigFrame;
    Xin.HW.NI.T.hTask_CO_TrigFrame = Task(T.taskName);
    Xin.HW.NI.T.hTask_CO_TrigFrame.createCOPulseChanTicks(...
        T.chan(1).deviceNames,              T.chan(1).chanIDs,...
        T.chan(1).chanNames,                T.chan(1).sourceTerminal,...
        T.chan(1).lowTicks,                 T.chan(1).highTicks,...
        T.chan(1).initialDelay,             T.chan(1).idleState);  
    Xin.HW.NI.T.hTask_CO_TrigFrame.cfgImplicitTiming(...
        T.time.sampleMode,                  T.time.sampsPerChanToAcquire);
    Xin.HW.NI.T.hTask_CO_TrigFrame.cfgDigEdgeStartTrig(...
        T.trigger.triggerSource,            T.trigger.triggerEdge);
    Xin.HW.NI.T.hTask_CO_TrigFrame.start();
    
% % Update Timer
%     T = NI.Task_CO_TrigUpdate;
%     Xin.HW.NI.T.hTask_CO_TrigUpdate = Task(T.taskName);
%     Xin.HW.NI.T.hTask_CO_TrigUpdate.createCOPulseChanTicks(...
%         T.chan(1).deviceNames,              T.chan(1).chanIDs,...
%         T.chan(1).chanNames,                T.chan(1).sourceTerminal,...
%         T.chan(1).lowTicks,                 T.chan(1).highTicks,...
%         T.chan(1).initialDelay,             T.chan(1).idleState);  
%     Xin.HW.NI.T.hTask_CO_TrigUpdate.cfgImplicitTiming(...
%         T.time.sampleMode,                  T.time.sampsPerChanToAcquire);
%     Xin.HW.NI.T.hTask_CO_TrigUpdate.cfgDigEdgeStartTrig(...
%         T.trigger.triggerSource,            T.trigger.triggerEdge);
%     Xin.HW.NI.T.hTask_CO_TrigUpdate.registerSignalEvent(...
%         @updateTest,                        'DAQmx_Val_CounterOutputEvent');
%     Xin.HW.NI.T.hTask_CO_TrigUpdate.start();
    hWaitbar =      waitbar(0, 'The recording will be triggered'); 
    tWait =         5;
    tStart =        tic;
    tNow =          toc(tStart);
    while tNow < tWait
        tNow =          toc(tStart);
        waitbar(tNow/tWait, hWaitbar,...
            ['The recording will be triggered in ',...
            sprintf('%d seconds', round(tWait-tNow)+1)] );    
        pause(1)
    end
    delete(hWaitbar);

% Start Trigger
    T = NI.Task_CO_TrigStart;
    Xin.HW.NI.T.hTask_CO_TrigStart = Task(T.taskName);
    Xin.HW.NI.T.hTask_CO_TrigStart.createCOPulseChanTicks(...
        T.chan(1).deviceNames,              T.chan(1).chanIDs,...
        T.chan(1).chanNames,                T.chan(1).sourceTerminal,...
        T.chan(1).lowTicks,                 T.chan(1).highTicks,...
        T.chan(1).initialDelay,             T.chan(1).idleState);
    Xin.HW.NI.T.hTask_CO_TrigStart.start();
    
%% LOG MSG
msg = [datestr(now, 'yy/mm/dd HH:MM:SS.FFF') '\tStartNIDAQ\tNI-DAQmx tasks initialized & triggered \r\n'];
updateMsg(Xin.D.Exp.hLog, msg);
